export const DASHBOARD_ACTIVE_JOB_LIMIT = 100;
export const DASHBOARD_ACTIVE_DISC_LIMIT = 100;
export const DASHBOARD_ACTIVITY_HISTORY_LIMIT = 20;
export const DASHBOARD_ACTIVITY_DETECTED_DISC_LIMIT =
  DASHBOARD_ACTIVE_DISC_LIMIT + DASHBOARD_ACTIVITY_HISTORY_LIMIT;
