PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_disc_inspections` (
	`id` text PRIMARY KEY,
	`optical_drive_id` text NOT NULL,
	`detected_disc_id` text,
	`media_generation` text NOT NULL,
	`media_capacity_bytes` integer,
	`stable_observation_count` integer,
	`settling_quiet_window_started_at` integer,
	`settling_started_at` integer,
	`settling_reset_count` integer,
	`is_current` integer DEFAULT true NOT NULL,
	`status` text DEFAULT 'running' NOT NULL,
	`phase` text DEFAULT 'settling' NOT NULL,
	`attempt_count` integer DEFAULT 1 NOT NULL,
	`consecutive_failure_count` integer DEFAULT 0 NOT NULL,
	`volume_label` text,
	`title_count` integer,
	`chapter_count` integer,
	`audio_stream_count` integer,
	`subtitle_stream_count` integer,
	`total_bytes` integer,
	`bytes_hashed` integer,
	`bytes_per_second` integer,
	`eta_seconds` integer,
	`retry_at` integer,
	`manual_retry_requested_at` integer,
	`reason_code` text,
	`diagnostic` text,
	`claim_token` text,
	`claim_updated_at` integer,
	`phase_started_at` integer NOT NULL,
	`attempt_started_at` integer NOT NULL,
	`started_at` integer NOT NULL,
	`completed_at` integer,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	CONSTRAINT `fk_disc_inspections_optical_drive_id_optical_drives_id_fk` FOREIGN KEY (`optical_drive_id`) REFERENCES `optical_drives`(`id`) ON DELETE RESTRICT,
	CONSTRAINT `fk_disc_inspections_detected_disc_id_detected_discs_id_fk` FOREIGN KEY (`detected_disc_id`) REFERENCES `detected_discs`(`id`) ON DELETE RESTRICT,
	CONSTRAINT "disc_inspections_id_not_null" CHECK("id" is not null),
	CONSTRAINT "disc_inspections_status_check" CHECK("status" in ('running', 'completed', 'failed', 'aborted')),
	CONSTRAINT "disc_inspections_phase_check" CHECK("phase" in ('settling', 'reading_metadata', 'hashing_content', 'confirming_media', 'retry_wait')),
	CONSTRAINT "disc_inspections_reason_check" CHECK("reason_code" is null or "reason_code" in ('no_medium', 'media_changed', 'drive_identity_changed', 'drive_unavailable', 'drive_not_ready', 'metadata_read_failed', 'invalid_metadata', 'content_size_failed', 'content_read_failed', 'invalid_content', 'worker_interrupted', 'operator_cancelled', 'unknown')),
	CONSTRAINT "disc_inspections_generation_check" CHECK(length("media_generation") between 1 and 64),
	CONSTRAINT "disc_inspections_settling_evidence_check" CHECK((("media_capacity_bytes" is null and "stable_observation_count" is null and "settling_quiet_window_started_at" is null and "settling_started_at" is null and "settling_reset_count" is null) or ("media_capacity_bytes" is null and "stable_observation_count" = 0 and "settling_quiet_window_started_at" is null and "settling_started_at" is not null and typeof("settling_reset_count") = 'integer' and "settling_reset_count" between 0 and 10000) or (typeof("media_capacity_bytes") = 'integer' and "media_capacity_bytes" > 0 and "media_capacity_bytes" <= 9000000000 and "media_capacity_bytes" % 2048 = 0 and typeof("stable_observation_count") = 'integer' and "stable_observation_count" between 1 and 3 and "settling_quiet_window_started_at" is not null and "settling_started_at" is not null and "settling_quiet_window_started_at" >= "settling_started_at" and typeof("settling_reset_count") = 'integer' and "settling_reset_count" between 0 and 10000)) and ("phase" <> 'settling' or "settling_started_at" is not null)),
	CONSTRAINT "disc_inspections_attempt_count_check" CHECK(typeof("attempt_count") = 'integer' and "attempt_count" > 0 and typeof("consecutive_failure_count") = 'integer' and "consecutive_failure_count" between 0 and 5 and "consecutive_failure_count" <= "attempt_count"),
	CONSTRAINT "disc_inspections_findings_check" CHECK(("title_count" is null or (typeof("title_count") = 'integer' and "title_count" >= 0)) and ("chapter_count" is null or (typeof("chapter_count") = 'integer' and "chapter_count" >= 0)) and ("audio_stream_count" is null or (typeof("audio_stream_count") = 'integer' and "audio_stream_count" >= 0)) and ("subtitle_stream_count" is null or (typeof("subtitle_stream_count") = 'integer' and "subtitle_stream_count" >= 0))),
	CONSTRAINT "disc_inspections_progress_check" CHECK(("total_bytes" is null or (typeof("total_bytes") = 'integer' and "total_bytes" >= 0)) and ("bytes_hashed" is null or (typeof("bytes_hashed") = 'integer' and "bytes_hashed" >= 0 and ("total_bytes" is null or "bytes_hashed" <= "total_bytes")))),
	CONSTRAINT "disc_inspections_estimate_check" CHECK(("bytes_per_second" is null) = ("eta_seconds" is null) and ("bytes_per_second" is null or (typeof("bytes_per_second") = 'integer' and "bytes_per_second" > 0 and typeof("eta_seconds") = 'integer' and "eta_seconds" >= 0))),
	CONSTRAINT "disc_inspections_claim_check" CHECK(("claim_token" is null) = ("claim_updated_at" is null) and ("claim_token" is null or "status" = 'running')),
	CONSTRAINT "disc_inspections_terminal_check" CHECK(("status" = 'running') = ("completed_at" is null) and ("status" = 'completed') = ("detected_disc_id" is not null)),
	CONSTRAINT "disc_inspections_retry_check" CHECK(("retry_at" is null or ("status" = 'running' and "phase" = 'retry_wait')) and ("manual_retry_requested_at" is null or ("status" = 'failed' and "is_current" = 1)))
);
--> statement-breakpoint
INSERT INTO `__new_disc_inspections`(`id`, `optical_drive_id`, `detected_disc_id`, `media_generation`, `media_capacity_bytes`, `stable_observation_count`, `settling_quiet_window_started_at`, `settling_started_at`, `settling_reset_count`, `is_current`, `status`, `phase`, `attempt_count`, `consecutive_failure_count`, `volume_label`, `title_count`, `chapter_count`, `audio_stream_count`, `subtitle_stream_count`, `total_bytes`, `bytes_hashed`, `bytes_per_second`, `eta_seconds`, `retry_at`, `manual_retry_requested_at`, `reason_code`, `diagnostic`, `claim_token`, `claim_updated_at`, `phase_started_at`, `attempt_started_at`, `started_at`, `completed_at`, `created_at`, `updated_at`) SELECT `id`, `optical_drive_id`, `detected_disc_id`, `media_generation`, `media_capacity_bytes`, `stable_observation_count`, `settling_quiet_window_started_at`, `settling_started_at`, `settling_reset_count`, `is_current`, `status`, `phase`, `attempt_count`, `consecutive_failure_count`, `volume_label`, `title_count`, `chapter_count`, `audio_stream_count`, `subtitle_stream_count`, `total_bytes`, `bytes_hashed`, `bytes_per_second`, `eta_seconds`, `retry_at`, `manual_retry_requested_at`, `reason_code`, `diagnostic`, `claim_token`, `claim_updated_at`, `phase_started_at`, `attempt_started_at`, `started_at`, `completed_at`, `created_at`, `updated_at` FROM `disc_inspections`;--> statement-breakpoint
DROP TABLE `disc_inspections`;--> statement-breakpoint
ALTER TABLE `__new_disc_inspections` RENAME TO `disc_inspections`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE UNIQUE INDEX `disc_inspections_current_drive_unique` ON `disc_inspections` (`optical_drive_id`) WHERE "disc_inspections"."is_current" = 1;--> statement-breakpoint
CREATE INDEX `disc_inspections_status_idx` ON `disc_inspections` (`status`,`updated_at`);